name: Checks

on:
  workflow_call:

jobs:
  checks:
    name: Run All Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Export environment variables
        env:
          OPENAI_API_KEY: "your-api-key"
        run: |
          echo "OPENAI_API_KEY=your-api-key" >> $GITHUB_ENV

      - name: Verify Environment Variable
        run: echo "OPENAI_API_KEY=your-api-key"

      - name: Run Black (Code Formatter)
        run: poetry run black --check .

      - name: Run isort (Import Sorter)
        run: poetry run isort --check-only .

      - name: Run Tests
        env:
          OPENAI_API_KEY: "your-api-key"
        run: poetry run pytest tests/ci --cov=.
