name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks-job:
    uses: ./.github/workflows/checks.yml

  deploy:
    needs: checks-job
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: curl -s -o /dev/null -w "" -X POST https://api.appliku.com/api/deploy_webhook/2677/3E1t39J47Aj3aoqWwm7cb12quleeryPOe4GVRrfoKRo
